11/20格式化
xiaoyu03/SEO-Admin-System pull request #10
Opened 2023-11-20 10:37 UTC by gopjj

2023-11-21 06:36 UTC, xiaoyu03 requested changes

2023-11-21 06:43 UTC, xiaoyu03 commented on client/src/pages/dashboard/css/module.css
> +.body {
这个module.css和dashboard.module.css有什么关系，我看app.tsx也引用了这里的，module.css算是我们的后缀，还需要前面有个文件名

2023-11-21 06:47 UTC, xiaoyu03 commented on client/src/pages/App.tsx
> +import image from "../resource/pictures/FOOHEAD.jpg";
import FooHeadImg from ..., 变量名含义更清晰

2023-11-21 06:57 UTC, xiaoyu03 commented on client/src/pages/App.tsx
> +        <div className="div-container">
建议把App放到pages/home/里表示主页，这里关于主页的style也都挪过来

2023-11-21 07:30 UTC, xiaoyu03 commented on client/src/pages/App.tsx
> +            <a href="#">
这个超链接锚点标签放在这里是为了后续实现点击头像跳转吗

2023-11-21 07:35 UTC, xiaoyu03 commented on client/src/pages/App.tsx
> +  const {} = theme.useToken();
多余的语句？

2023-11-22 02:59 UTC, xiaoyu03 commented on package.json
> +{
这几个package.json删掉，在client目录下执行yarn add命令

2023-11-22 03:05 UTC, xiaoyu03 commented on client/src/pages/Login/component/login.tsx
> +                <CustomCardTitle title="账号登录" />
我看CustomCardTitle只有这里一处引用，是不是不需要专门给他写的react 组件，直接把div写在这

2023-11-22 03:05 UTC, xiaoyu03 commented on client/src/pages/Login/component/login.tsx
> +              <div className={style.cardWrapper}>
这下面包装的是form，这个class叫formwrapper是不是更贴切

2023-11-22 03:06 UTC, xiaoyu03 commented on client/src/pages/Login/component/login.tsx
> +              <div className={style.registerStyle}>
style.register就行

2023-11-22 03:07 UTC, xiaoyu03 commented on client/src/pages/Login/component/header.tsx
>  export default App;
这行可以删了

2023-11-22 03:07 UTC, xiaoyu03 commented on client/src/pages/Login/component/header.tsx
> +export const App: React.FC = () => {
export const Header

2023-11-22 08:19 UTC, gopjj commented on client/src/pages/NoteTrack/css/module.css
> +.tab-style{
done

2023-11-22 08:20 UTC, gopjj commented on client/src/pages/dashboard/dashboard.tsx
>  import type { TabsProps } from "antd";
done

2023-11-22 08:20 UTC, gopjj commented on client/src/pages/dashboard/card/datacard.module.css
> +.cardText {
done

2023-11-22 08:20 UTC, gopjj commented on client/src/pages/dashboard/css/module.css
> +.body {
done

2023-11-22 08:54 UTC, gopjj commented on client/src/pages/App.tsx
> +import image from "../resource/pictures/FOOHEAD.jpg";
done

2023-11-22 09:14 UTC, gopjj commented on client/src/pages/App.tsx
> +        <div className="div-container">
done

2023-11-22 09:15 UTC, gopjj commented on client/src/pages/App.tsx
> +            <a href="#">
对的 实现个人主页的跳转

2023-11-22 09:17 UTC, gopjj commented on client/src/pages/Login/component/header.tsx
>  export default App;
done

2023-11-22 09:22 UTC, gopjj commented on client/src/pages/App.tsx
> +  const {} = theme.useToken();
done

2023-11-22 09:23 UTC, gopjj commented on package.json
> +{
是一整个文件删掉嘛？

2023-11-22 09:41 UTC, gopjj commented on client/src/pages/Login/component/login.tsx
> +                <CustomCardTitle title="账号登录" />
done

2023-11-22 09:44 UTC, gopjj commented on client/src/pages/Login/component/login.tsx
> +              <div className={style.registerStyle}>
done

2023-11-22 09:44 UTC, gopjj commented on client/src/pages/Login/component/header.tsx
> +export const App: React.FC = () => {
已删除 直接写到login里了

2023-11-22 09:44 UTC, gopjj commented on client/src/pages/Login/component/login.tsx
> +              <div className={style.cardWrapper}>
done

2023-11-22 14:02 UTC, xiaoyu03 commented on client/src/pages/App.tsx
> +import image from "../resource/pictures/FOOHEAD.jpg";
image不是一个足够清晰的变量名

2023-11-22 14:04 UTC, xiaoyu03 commented on client/src/pages/App.tsx
> +import "./dashboard/componet/styles/module.css";
这个module.css可以有个清晰的命名，可以把和app.tsx有关的拆出来，另一部分和dashboard有关的，放到相应的module.css文件里

2023-11-22 14:05 UTC, xiaoyu03 commented on client/src/pages/NoteTrack/demodualAxes.tsx
> +import "../dashboard/componet/styles/module.css";
从名字无法看出这个module.css里面放的是啥

2023-11-22 14:08 UTC, xiaoyu03 commented on client/src/pages/Login/component/login.tsx
> +
多余的空行，只需要空一行即可

2023-11-22 14:11 UTC, xiaoyu03 commented on client/src/pages/NoteTrack/componet/noteOptm.tsx
> +import styles from "./styles/track.module.css"
因为这里是noteOptm.tsx, 而你引入的是track.module.css，不是相同的名字，建议import trackStyle from ... 会更清晰

2023-11-22 14:12 UTC, xiaoyu03 commented on client/src/pages/NoteTrack/componet/noteOptm.tsx
> +import styles from "./styles/track.module.css"
或者，单独新建一个文件，noteOptm.module.css, 把和它有关的放进去，不要混着引用。各个组件最好只引用自己的module.css

2023-11-22 14:26 UTC, xiaoyu03 approved these changes

2023-11-23 03:54 UTC, gopjj commented on client/src/pages/App.tsx
> +import "./dashboard/componet/styles/module.css";
done

2023-11-23 03:54 UTC, gopjj commented on client/src/pages/NoteTrack/demodualAxes.tsx
> +import "../dashboard/componet/styles/module.css";
done

2023-11-23 03:55 UTC, gopjj commented on client/src/pages/Login/component/login.tsx
> +
done

2023-11-23 09:52 UTC, merged